title = "Gariany.com"
enableRobotsTXT = true

baseURL = "https://www.gariany.com/"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  #Favicon for site
  favicon = "/favicon.ico"
  talkyardServerUrl = "https://comments-for-www-gariany-com.talkyard.net"
  # talkyardScriptUrl = "/js/talkyard-comments.min.js"
  talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"
  # SEO parameters
  description = "Personal blog and portfolio of Elad Gariany"
  keywords = ["blog", "technology", "programming", "web development"]
  author = "Elad Gariany"
  language = "en"
  googleSiteVerification = "" # Add your Google Search Console verification code
  # Social media
  twitter = "@elad_g" # Replace with your Twitter handle
  github = "eladg" # Replace with your GitHub username

[permalinks]
  posts = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML"]
